ARG MONGO_IMAGE_REPO
ARG MONGO_IMAGE_TAG

FROM ${MONGO_IMAGE_REPO}:${MONGO_IMAGE_TAG}

RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list && \
    sed -i 's/security-cdn.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list

EXPOSE 27017